In [2]:
import numpy as np
import pandas as pd
from collections import Counter

In [3]:
#matriz 1X10 com 10 valores com intervalo de 2
np_arange = np.arange(1, 20, 2)
np_arange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [5]:
#transformando pra uma matriz 2x5
np_reshape = np_arange.reshape(2, 5)
np_reshape

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [13]:
#duas matrizes bidimensionais com valores aleatórios de 1 a 100
np_random1 = np.random.randint(100, size=(4, 4))
np_random2 = np.random.randint(100, size=(4, 4))
print (np_random1, '\n')
print (np_random2)

[[28 88 60 53]
 [93 47 27 41]
 [ 7 59 77  5]
 [71 68 27 36]] 

[[42 43 63 92]
 [23 62 54 69]
 [84  3 87 36]
 [29 75 55 44]]


In [16]:
#transpostas
np_transpose1 = np_random1.transpose()
print(np_transpose1, '\n')
np_transpose2 = np_random2.transpose()
print(np_transpose2)

[[28 93  7 71]
 [88 47 59 68]
 [60 27 77 27]
 [53 41  5 36]] 

[[42 23 84 29]
 [43 62  3 75]
 [63 54 87 55]
 [92 69 36 44]]


In [24]:
#multiplicação de matrizes
np_mult = (np_random1)*(np_random2)
print (np_mult)

[[1176 3784 3780 4876]
 [2139 2914 1458 2829]
 [ 588  177 6699  180]
 [2059 5100 1485 1584]]


In [28]:
#salvando as matrizes de entrada e saida em .npy e .npz
nHIGH = np_random1
np.save('/home/nataliasa/09-curso-numpy/exercícios/Natalia/random1',nHIGH) 
np.savez_compressed('/home/nataliasa/09-curso-numpy/exercícios/Natalia/random1_2',nHIGH=nHIGH)

nHIGH = np_random2
np.save('/home/nataliasa/09-curso-numpy/exercícios/Natalia/random2',nHIGH) 
np.savez_compressed('/home/nataliasa/09-curso-numpy/exercícios/Natalia/random2_2',nHIGH=nHIGH)

nHIGH = np_transpose1
np.save('/home/nataliasa/09-curso-numpy/exercícios/Natalia/transpose1',nHIGH) 
np.savez_compressed('/home/nataliasa/09-curso-numpy/exercícios/Natalia/transpose1_2',nHIGH=nHIGH)

nHIGH = np_transpose2
np.save('/home/nataliasa/09-curso-numpy/exercícios/Natalia/transpose2',nHIGH) 
np.savez_compressed('/home/nataliasa/09-curso-numpy/exercícios/Natalia/transpose2_2',nHIGH=nHIGH)

nHIGH = np_mult
np.save('/home/nataliasa/09-curso-numpy/exercícios/Natalia/mult',nHIGH) 
np.savez_compressed('/home/nataliasa/09-curso-numpy/exercícios/Natalia/mult_2',nHIGH=nHIGH)

In [31]:
#tamanho dos arquivos gerados
!ls -lh /home/nataliasa/09-curso-numpy/exercícios/Natalia/random1.npy
!ls -lh /home/nataliasa/09-curso-numpy/exercícios/Natalia/random2.npy
!ls -lh /home/nataliasa/09-curso-numpy/exercícios/Natalia/transpose1.npy
!ls -lh /home/nataliasa/09-curso-numpy/exercícios/Natalia/transpose2.npy
!ls -lh /home/nataliasa/09-curso-numpy/exercícios/Natalia/mult.npy
!ls -lh /home/nataliasa/09-curso-numpy/exercícios/Natalia/random1_2.npz

-rw-rw-r-- 1 nataliasa nataliasa 256 set 14 11:54 /home/nataliasa/09-curso-numpy/exercícios/Natalia/random1.npy
-rw-rw-r-- 1 nataliasa nataliasa 256 set 14 11:54 /home/nataliasa/09-curso-numpy/exercícios/Natalia/random2.npy
-rw-rw-r-- 1 nataliasa nataliasa 256 set 14 11:54 /home/nataliasa/09-curso-numpy/exercícios/Natalia/transpose1.npy
-rw-rw-r-- 1 nataliasa nataliasa 256 set 14 11:54 /home/nataliasa/09-curso-numpy/exercícios/Natalia/transpose2.npy
-rw-rw-r-- 1 nataliasa nataliasa 256 set 14 11:54 /home/nataliasa/09-curso-numpy/exercícios/Natalia/mult.npy
-rw-rw-r-- 1 nataliasa nataliasa 227 set 14 11:54 /home/nataliasa/09-curso-numpy/exercícios/Natalia/random1_2.npz


In [44]:
#duas matrizes bidimensionais com valores aleatórios de 1 a 100
np_random3 = np.random.randint(100, size=(4, 4))
np_random4 = np.random.randint(100, size=(4, 4))
print (np_random3, '\n')
print (np_random4, '\n')

#Combinando as matrizes linha a linha
print ("Combinando linha a linha: \n")
print (np.concatenate([np_random3, np_random4], axis=1))

[[41 36 23 52]
 [75  3 89 81]
 [98 19 87 66]
 [71 51 75 58]] 

[[10 26 32 52]
 [56 27  0 90]
 [52  4 68 26]
 [61 34 88 63]] 

Combinando linha a linha: 

[[41 36 23 52 10 26 32 52]
 [75  3 89 81 56 27  0 90]
 [98 19 87 66 52  4 68 26]
 [71 51 75 58 61 34 88 63]]


In [64]:
#vetor nulo de tamanho 10
np_null = np.zeros(10, dtype='int8')
print (np_null)

[0 0 0 0 0 0 0 0 0 0]


In [59]:
#Tamanho da memória e bytes
print(np_null.size)
print(np_null.nbytes) 

10
10


In [66]:
#vetor nulo de tamanho 10, mas o quinto valor é 1
np_null1 = np.zeros(10, dtype='int8')
np_null1[4] =  1
print (np_null1)

[0 0 0 0 1 0 0 0 0 0]


In [132]:
#vetor com 10 valores aleatórios entre 10 e 49
#np_vector = np.arange(10, 50)
np_vector=np.linspace(10,49,10, dtype = 'int') 
print (np_vector)

[10 14 18 23 27 31 36 40 44 49]


In [133]:
#inverter o primeiro elemento
print(np_vector[::-1])

[49 44 40 36 31 27 23 18 14 10]


In [100]:
#matriz 3x3 com valores de 0 a 8
matriz3x3 = np.arange(0, 9)
matriz3x3 = matriz3x3.reshape(3, 3)
print (matriz3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [124]:
#matriz identidade 3x3
np_identidade = np.eye(3)
print (np_identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [123]:
#matriz aleatória 3x3x3
np_random = np.random.randint(100, size=(3, 3, 3))
print (np_random)

[[[98 67 77]
  [86  5 75]
  [12 64 69]]

 [[99 87 11]
  [47 51 30]
  [60 43  5]]

 [[56  0 61]
  [ 2 58 68]
  [ 1 44 63]]]


In [117]:
#matriz 10x10 com valores aleatórios
np_random10 = np.random.randint(1000, size=(10, 10))
print (np_random10)

#achar o valor mínimo e máximo da matriz acima
np_max = np_random10.max()
np_min = np_random10.min()
print ("Valor mínimo:", np_min, "Valor máximo:", np_max )

[[348  32 446 336 934 851 414 158 984  96]
 [667 454 619 977 205 106 691  72 751  79]
 [331 825 914 580 682  59 707  99 388 433]
 [857 140 438  43 432 178  58 932 699 214]
 [933 824 366 331 192 177 993 354 135 159]
 [477 468 176 196 150 735 638 774 719  53]
 [267 734 188 351 363  49 784 624 232 530]
 [593 166 653  31 352 732  89 897 339 107]
 [490 233 798 275 456 812 902 717 430 971]
 [277 210 276 862 507 590 733 206 584 297]]
Valor mínimo: 31 Valor máximo: 993


In [126]:
#Vetor aleatório de tamanho 30
np_vector30 = np.random.random(30)
print (np_vector30, '\n')

#valor médio
np_mean = np_vector30.mean()
print ("Valor médio: ", np_mean)

[0.94511956 0.77990929 0.2957036  0.30038085 0.35728683 0.5840702
 0.90718128 0.90691674 0.07727115 0.83497595 0.39712578 0.75385352
 0.46663736 0.24473091 0.85139367 0.13209577 0.69311008 0.44985606
 0.98453574 0.19510987 0.09678551 0.64058612 0.45592723 0.10016116
 0.29135692 0.3495416  0.49853081 0.81133474 0.41030189 0.15061292] 

Valor médio:  0.49874677002086726


In [134]:
#Matriz 2d com 1 na borda e 0 dentro
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [140]:
#matriz 5x5 com 1, 2, 3, 4 logo abaixo da diagonal
x = np.zeros((5,5))
x[1,0] = 1
x[2,1] = 2
x[3,2] = 3
x[4,3] = 4
print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [6]:
#matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)
imagem = np.random.randint(low=1, high=256, size=(720, 480, 3))
print (imagem)

[[[210 144  22]
  [  7 244 240]
  [255  24 204]
  ...
  [ 68  30 254]
  [  4  83  81]
  [128 119  39]]

 [[  8 189 140]
  [200 228 229]
  [215  92  59]
  ...
  [196  76 222]
  [242  58 232]
  [246 134 141]]

 [[142 106 165]
  [ 49 127 113]
  [172 185  36]
  ...
  [231 171   8]
  [ 54 131  70]
  [ 84   5 170]]

 ...

 [[253 198 118]
  [168 170   6]
  [194  51  95]
  ...
  [ 45 222  35]
  [219 217 202]
  [177  50  68]]

 [[254  25 101]
  [ 49 140   3]
  [109  67  45]
  ...
  [109   7  55]
  [247   3 235]
  [202  62  43]]

 [[158 207 136]
  [138 224 102]
  [ 77  91 188]
  ...
  [108  28 166]
  [  2 147 179]
  [  6 217 189]]]


In [157]:
np_media = np.random.randint(10, size=(10,10))
print (np_media, '\n') #matriz aleatória 10x10

print ("Média de cada linha: ", np_media.mean(1), '\n')

print ("Valor mais frequente: ", np.argmax(np.bincount(np_media.flat)))

[[7 0 2 6 9 2 9 3 3 1]
 [6 3 0 1 2 7 4 2 6 4]
 [3 5 4 7 0 5 3 1 9 3]
 [7 2 0 9 0 0 4 4 5 1]
 [7 2 6 9 1 8 5 0 4 6]
 [7 1 5 4 6 7 6 3 9 7]
 [9 2 3 8 7 6 6 6 8 3]
 [2 1 7 5 7 1 7 8 1 8]
 [1 3 2 1 6 2 2 7 5 0]
 [7 3 7 1 5 7 8 4 4 7]] 

Média de cada linha:  [4.2 3.5 4.  3.2 4.8 5.5 5.8 4.7 2.9 5.3] 

Valor mais frequente:  7


In [163]:
#criando matriz a partir de um csv
matriz_termica = pd.read_csv('/home/nataliasa/sprint1/data/tags/Tags_de_01segundo/CFO.AI-112-2MA.PV.txt', sep = ';', low_memory=False, header=None).values
print (matriz_termica)

[['ts' 'value']
 ['01-JAN-20 00:00:00.0' '206.642']
 ['01-JAN-20 00:00:30.0' '207.191']
 ...
 ['28-JUL-20 23:58:30.0' '255.249']
 ['28-JUL-20 23:59:00.0' '255.062']
 ['28-JUL-20 23:59:30.0' '251.924']]
