# Crie um array com 10 elementos usando a função arange

In [2]:
import numpy as np

In [3]:

arr = np.arange(1,11,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


# Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape

In [4]:
arr_re = arr.reshape((2,5))
print(arr_re)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Crie duas matrizes bidimensionais com valores aleatórios

In [5]:
matriz_1 = np.random.rand(5,4)
matriz_1

array([[0.28662073, 0.82897333, 0.07668621, 0.17198998],
       [0.76397917, 0.15263452, 0.72176122, 0.05733409],
       [0.52106485, 0.01593686, 0.105784  , 0.18087894],
       [0.74684707, 0.20044311, 0.1996304 , 0.93633651],
       [0.31465193, 0.061681  , 0.19549705, 0.56662765]])

In [6]:
matriz_2 = np.random.randint(0, 100, (5,4))
matriz_2

array([[40, 40, 26, 90],
       [15, 98, 30, 14],
       [19, 98, 64, 34],
       [30, 88, 69, 26],
       [61, 82, 64, 34]])

# Calcule a transposta de cada matriz

In [7]:
tmatriz_1 = matriz_1.T
tmatriz_1

array([[0.28662073, 0.76397917, 0.52106485, 0.74684707, 0.31465193],
       [0.82897333, 0.15263452, 0.01593686, 0.20044311, 0.061681  ],
       [0.07668621, 0.72176122, 0.105784  , 0.1996304 , 0.19549705],
       [0.17198998, 0.05733409, 0.18087894, 0.93633651, 0.56662765]])

In [8]:
tmatriz_2 = matriz_2.T
tmatriz_2

array([[40, 15, 19, 30, 61],
       [40, 98, 98, 88, 82],
       [26, 30, 64, 69, 64],
       [90, 14, 34, 26, 34]])

# multiplique as duas matrizes

In [9]:
multiplica = matriz_1 * matriz_2
multiplica

array([[11.46482901, 33.15893313,  1.99384144, 15.4790986 ],
       [11.45968754, 14.95818301, 21.65283665,  0.80267721],
       [ 9.90023211,  1.56181237,  6.77017573,  6.14988396],
       [22.40541197, 17.63899348, 13.77449738, 24.34474916],
       [19.19376789,  5.05784169, 12.51181097, 19.26534007]])

# Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?

matriz de entrada 1 = matriz_1    
matriz de entrada 2 = matriz_2    
matriz de saída = multiplica
  
path = "/home/melaniegisselurdangaringamarra/Documentos/git_workspace/09-curso-numpy-master/melanie_exercicios"    

In [15]:
!touch salva_matent1.txt
np.savetxt('salva_matent1.txt',matriz_1) 

In [29]:
m1 = np.loadtxt('salva_matent1.txt') 
print("matriz1: ",m1)

matriz1:  [[0.28662073 0.82897333 0.07668621 0.17198998]
 [0.76397917 0.15263452 0.72176122 0.05733409]
 [0.52106485 0.01593686 0.105784   0.18087894]
 [0.74684707 0.20044311 0.1996304  0.93633651]
 [0.31465193 0.061681   0.19549705 0.56662765]]


In [16]:
!touch salva_matent2.txt
np.savetxt('salva_matent2.txt',matriz_2) 

In [30]:
m2 = np.loadtxt('salva_matent2.txt') 
print("matriz2: ",m2)

matriz2:  [[40. 40. 26. 90.]
 [15. 98. 30. 14.]
 [19. 98. 64. 34.]
 [30. 88. 69. 26.]
 [61. 82. 64. 34.]]


In [17]:
!touch salva_saida.txt
np.savetxt('salva_saida.txt',multiplica) 

In [31]:
m3 = np.loadtxt('salva_saida.txt') 
print("matriz3: ",m3)

matriz3:  [[11.46482901 33.15893313  1.99384144 15.4790986 ]
 [11.45968754 14.95818301 21.65283665  0.80267721]
 [ 9.90023211  1.56181237  6.77017573  6.14988396]
 [22.40541197 17.63899348 13.77449738 24.34474916]
 [19.19376789  5.05784169 12.51181097 19.26534007]]


In [34]:
#print(my_array)
#print(matriz_1.ndim) -> dimensiones = 2
#print(matriz_1.shape) -> (5,4)
#print(matriz_1.size) -> 5x4 = 20
#print(matriz_1.flags)
#print(matriz_1.itemsize) -> 8
print('Tamanho em bytes das matrizes:')
print(f'matriz_1 = {m1.nbytes}') 
print(f'matriz_2 = {m2.nbytes}') 
print(f'matriz_saida = {m3.nbytes}') 

Tamanho em bytes das matrizes:
matriz_1 = 160
matriz_2 = 160
matriz_saida = 160


# Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linha

In [35]:
mat1 = np.random.randint(0, 20, (3,2))
mat1

array([[16,  0],
       [ 0, 14],
       [18, 16]])

In [36]:
mat2 = np.random.randint(30, 40, (2,2))
mat2

array([[37, 33],
       [34, 35]])

In [37]:
np.vstack([mat1, mat2])

array([[16,  0],
       [ 0, 14],
       [18, 16],
       [37, 33],
       [34, 35]])

# Crie um vetor nulo de tamanho 10

In [41]:
zeros = np.zeros(10,dtype=np.int64) 

print("np.zeros: ",zeros)

np.zeros:  [0 0 0 0 0 0 0 0 0 0]


# Como encontrar o tamanho da memória de qualquer matriz

In [43]:
print("%d bytes" % (zeros.size * zeros.itemsize))

80 bytes


In [44]:
zeros.nbytes

80

# Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1

In [47]:
nulo = np.zeros(10, dtype=np.int64)
nulo

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
nulo[4] = 5

In [49]:
nulo

array([0, 0, 0, 0, 5, 0, 0, 0, 0, 0])

# Crie um vetor com valores que variam de 10 a 49

In [58]:
vet = np.arange(10,50,1)
vet
#print(type(vet))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# Inverter um vetor (o primeiro elemento se torna o último)

In [61]:
vet_rev = np.flip(vet, axis=None)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [55]:
vet_rev = list(reversed(vet))
print(vet_rev)


[49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


# Crie uma matriz 3x3 com valores que variam de 0 a 8

In [65]:
mat = np.arange(0,9,1)
mat33 = mat33.reshape((3,3))
mat33

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Crie uma matriz de identidade 3x3

In [67]:
n=np.identity(5) 
print("identidade: ",n)

identidade:  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Crie uma matriz 3x3x3 com valores aleatórios

In [76]:
n=np.linspace(1,27,27) 
mat333 = n.reshape((3,3,3))
mat333

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]]])

# Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo

In [83]:
aleat = np.random.randint(0, 100, (10,10))
aleat

array([[40,  0, 31, 85,  6, 61, 38, 71, 45, 27],
       [67, 99, 48, 52, 24, 22, 79, 58, 96, 63],
       [22, 39, 89, 68, 34, 53, 78, 56, 96, 94],
       [32, 40, 58, 38, 23, 50, 95, 58, 32, 54],
       [17, 68, 31, 94, 88,  8,  3, 88,  8, 16],
       [85, 66, 59,  1, 99, 36, 67, 76, 31,  6],
       [23, 30, 46, 75,  7, 81, 68, 81, 80, 11],
       [93, 80, 64, 80, 31,  7,  6, 56, 57, 54],
       [35, 31, 62, 73, 36, 57, 54,  1, 92, 54],
       [37, 11, 36, 51, 18, 55, 79, 80, 16, 32]])

In [85]:
minimo = aleat.min()
minimo

0

In [86]:
maximo = aleat.max()
maximo

99

# Crie um vetor aleatório de tamanho 30 e encontre o valor médio

In [89]:
vetor = np.random.randint(20,50,30)
vetor

array([22, 24, 40, 45, 37, 32, 24, 41, 32, 43, 47, 39, 30, 42, 23, 41, 28,
       38, 48, 45, 42, 24, 31, 33, 41, 23, 34, 27, 32, 34])

In [90]:
media = vetor.mean()
media

34.733333333333334

# Crie uma matriz 2D com 1 na borda e 0 dentro

In [113]:
x = np.ones((5,5))
print("Matriz original:")
print(x)
print("1 na borda e 0 dentro")
x[1:-1,1:-1] = 0
print(x)

Matriz original:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 na borda e 0 dentro
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [104]:
mat = np.zeros((5,5))
mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [105]:
mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [106]:
mat[0][:]=1
mat

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [109]:
mat[:][len(mat)-1:len(mat)]=1
mat

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [112]:
mat[0:len(mat)][len(mat)-1:len(mat)]=1
mat

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

...

# Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal

In [115]:
arr1 = np.zeros(25).reshape((5,5))
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [118]:
print(len(arr1))

5


In [120]:
cont = 0
for i in range(0,len(arr1)-1):
    cont += 1
    arr1[i+1][i] = cont

arr1

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

# Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)

In [123]:
M = [
  [(0, 0, 255), (0, 255, 0)],
  [(255, 0, 0), (0, 0, 0)]
]
"""
formato (B, G, R)
1er pixel es rojo
2do pixel es verde
3er pixel es azul
4to pixel es negro
"""
M

[[(0, 0, 255), (0, 255, 0)], [(255, 0, 0), (0, 0, 0)]]

# Subtrair a média de cada linha de uma matriz

In [124]:
m = np.random.randint(0, 100, (10,10))
m

array([[ 4, 40, 58, 28, 19, 36, 85, 43, 22, 22],
       [37, 74, 36, 89, 19, 21, 99,  6, 70, 13],
       [26, 87, 78, 76, 61, 42, 89, 77, 52, 50],
       [85, 49, 39, 19, 70, 51, 18, 71, 76, 38],
       [23, 33, 13,  2, 74, 93, 55, 57, 82, 72],
       [86, 74, 89, 41, 16,  0, 69, 43, 32, 94],
       [74, 35, 90, 55, 56,  8, 70, 85, 89,  6],
       [28, 15, 97, 69, 81, 80, 19,  4,  2, 30],
       [14, 49, 90, 73, 91, 65,  7, 75, 58, 35],
       [ 1, 58, 21,  0, 33, 22, 24, 91, 47, 36]])

In [131]:
#m[0][:].mean(axis=1)
media = []

for i in range (0,len(m)-1):
    media.append(m[i][:].mean())

media

[35.7, 46.4, 63.8, 51.6, 50.4, 54.4, 56.8, 42.5, 55.7]

# Como encontrar o valor mais frequente em uma matriz?

In [134]:
# achar o valor mais frequente para um array:
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())
# no caso de matriz, aplicar o método anterior linha a linha, 
# crear um vetor armazenanando o valor mais frequente de cada linha
# por último, calcular o valor mais frequente de esse vetor

# Crie uma matriz a partir de um arquivo

In [141]:
import pandas as pd

df = pd.read_csv('arquivo.csv', sep=';',header=None)

df.values 

array([[ 1,  6, 20,  9],
       [ 2,  7, 30,  2],
       [ 3,  8, 40,  7],
       [ 4,  9, 50,  3],
       [ 5, 10, 60,  6]])

# crie uma matriz com valores aletaórios e salve para um arquivo

In [142]:
mat = np.random.randint(0, 100, (5,5))
mat

array([[40, 55, 94, 50, 62],
       [ 1, 24, 62, 51, 85],
       [96, 44, 93, 59, 23],
       [61, 77, 29, 93, 15],
       [90,  0, 80,  8, 80]])

In [143]:
!touch salva_matriz.txt
np.savetxt('salva_matriz.txt',mat) 

In [144]:
!cat salva_matriz.txt

4.000000000000000000e+01 5.500000000000000000e+01 9.400000000000000000e+01 5.000000000000000000e+01 6.200000000000000000e+01
1.000000000000000000e+00 2.400000000000000000e+01 6.200000000000000000e+01 5.100000000000000000e+01 8.500000000000000000e+01
9.600000000000000000e+01 4.400000000000000000e+01 9.300000000000000000e+01 5.900000000000000000e+01 2.300000000000000000e+01
6.100000000000000000e+01 7.700000000000000000e+01 2.900000000000000000e+01 9.300000000000000000e+01 1.500000000000000000e+01
9.000000000000000000e+01 0.000000000000000000e+00 8.000000000000000000e+01 8.000000000000000000e+00 8.000000000000000000e+01
