In [180]:
!conda install numpy

Solving environment: \ 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/noarch::tensorflow-estimator==2.0.0=pyh2649769_0
  - defaults/noarch::tensorboard==2.0.0=pyhb38c66f_1
  - defaults/linux-64::tensorflow==2.0.0=gpu_py37h768510d_0
  - defaults/linux-64::tensorflow-base==2.0.0=gpu_py37h0ec5d1f_0
  - defaults/linux-64::tensorflow-gpu==2.0.0=h0d30ee6_0
  - defaults/linux-64::keras==2.3.1=0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: | 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/noarch::tensorflow-estimator==2.0.0=pyh2649769_0
  - defaults/noarch::tensorboard==2.0.0=pyhb38c66f_1
  - defaults/linux-64::tensorflow==2.0.0=gpu_py37h768510d_0
  - defaults/li

In [181]:
import numpy as np
import pandas as pd

# criando array com valores iguais

In [190]:
n = np.ones((6,3,2))
print(type(n))
print("np.ones: ",n)

<class 'numpy.ndarray'>
np.ones:  [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


# criando array com zeros

In [203]:
n=np.zeros((2,3,4),dtype=np.int64) 

print(n.dtype)

print("np.zeros: ",n)

int64
np.zeros:  [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


# criando array com valores aleatorios 

In [193]:
n=np.random.random((4,5,6)) 
print("random.random: ",n)

random.random:  [[[7.99920842e-01 6.86527997e-01 1.47101461e-01 4.55524545e-01
   1.95779499e-01 7.47178002e-01]
  [8.53807522e-01 5.80316792e-01 6.08806444e-01 1.48963455e-01
   9.89093931e-01 3.85033292e-01]
  [3.53490438e-01 6.99959847e-01 7.83442573e-01 1.14375205e-02
   8.21790307e-01 2.03095917e-01]
  [6.48610475e-01 9.73332020e-01 2.62226461e-02 2.20170613e-01
   7.24269511e-01 3.01584269e-01]
  [3.24105150e-01 3.44233554e-01 9.04312695e-01 7.25149558e-01
   6.95666928e-01 3.64944134e-01]]

 [[3.29049400e-02 1.81768783e-01 5.13970021e-01 4.18800487e-01
   6.91142597e-01 5.44695497e-01]
  [6.68974351e-01 3.04617823e-01 4.60359538e-01 7.27039116e-01
   6.10377245e-01 3.36494602e-01]
  [7.38844327e-01 5.68131138e-01 7.05616663e-04 9.07828311e-01
   4.36970360e-01 5.29262158e-01]
  [8.68539172e-01 4.81965197e-01 2.12059155e-01 9.02467739e-02
   6.54717717e-01 4.38452174e-01]
  [6.44194416e-01 2.44386588e-02 5.31159134e-02 8.16927055e-01
   4.96266242e-01 8.39744522e-01]]

 [[5.90102

# criando array vazias

In [148]:

n=np.empty((3,2)) 
print("empty: ",n)

empty:  [[0. 0.]
 [0. 0.]
 [0. 0.]]


# criando array com valores sequenciais

In [149]:

n=np.arange(10,25,5) 
print("arange: ",n)

arange:  [10 15 20]


In [205]:
n=np.arange(1,10,4) 
print("arange: ",n)

arange:  [1 5 9]


* matriz com valores igualmente espacados em um intervalo
* criando matriz identidade, 

In [209]:
n=np.linspace(0,1,100) 
print("linspace: ",n)

n = np.eye(22) 
print("np.eye: ",n)
print('\n')
n = np.identity(5) 
print("\n np.identity: ",n)

linspace:  [0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888

# mudando o tipo da matriz
* bool_
* int_
* intc
* intp
* int8
* int16
* int32
* int64
* uint8
* uint16
* uint32
* uint64
* float_
* float16
* float32
* float64
* complex_
* complex64
* complex128

In [233]:
z=np.array([1.2345678999, 2.33, 3.55, 4.4], dtype='complex128')
print(z)
print(z.nbytes)

[1.2345679+0.j 2.33     +0.j 3.55     +0.j 4.4      +0.j]
64


In [238]:
z=np.array([9223372036854775805, 9223372036854775806, 9223372036854775807, 9999999999999999999,17999999999999999999,18000000000000000000,18000000000000000001], dtype='int64')
z                                                                                                        


OverflowError: Python int too large to convert to C long

In [239]:
z=np.array([9223372036854775805, 9223372036854775806, 9223372036854775807, 9999999999999999999,17999999999999999999,18000000000000000000], dtype='uint32')
z

array([4294967293, 4294967294, 4294967295, 2313682943, 3305635839,
       3305635840], dtype=uint32)

# informação sobre matrizes

* dimensoes
* formato
* quantidade de elementos
* layout de memoria
* tamanho de um elemento em bytes
* tamanho total do array em bytes

In [240]:
my_array=np.full((12,12),70)
print(my_array)
print(my_array.ndim)
print(my_array.shape)
print(my_array.size)
print(my_array.flags)
print(my_array.itemsize)
print(my_array.nbytes) 

[[70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]]
2
(12, 12)
144
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

8
1152


# mudando o formato - reshape

In [241]:
print(my_array) 

[[70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]]


In [242]:
zz=my_array.reshape(1,144)
print(zz) 

[[70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70
  70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70
  70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70
  70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70
  70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70
  70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70]]


# slicing de array
* cinco primeiros
* após quinto elemento
* elementos no meio da matriz
* pulando um elemento
* pulando um elemento comecando do elemento 1
* lista reversa
* lista reversa , pulando um elemento comecando do quinto elemento

In [158]:
x = np.arange(10)
print(x)
print(x[:5]) 
print(x[5:]) 
print(x[4:7]) 
print(x[::2])
print(x[1::2])
print(x[::-1])
print(x[5::-2])    

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


# Matriz multidimensional

In [244]:
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5)) 

In [245]:
x2

array([[4, 4, 0, 2],
       [4, 7, 7, 9],
       [5, 1, 5, 9]])

# slice de matriz multidimensional
* virgula separa qual dimensão será aplicado o slice
* duas linhas e 3 colunas
* todas as linhas pulando uma coluna
* ordem reversa
* primeira coluna
* primeira linha

In [246]:
print(x2[:2, :3])
print(x2[:3, ::2])
print(x2[::-1, ::-1])
print(x2[:, 0])
print(x2[0, :])

[[4 4 0]
 [4 7 7]]
[[4 0]
 [4 7]
 [5 5]]
[[9 5 1 5]
 [9 7 7 4]
 [2 0 4 4]]
[4 4 5]
[4 4 0 2]


# numpy represent variaveis por referencia
* fazendo slice de uma matriz para uma nova matriz, mantem a referencia para o valor original

In [247]:
x2_sub = x2[:2, :2] 
print(x2_sub)
x2_sub[0, 0] = 99 
print(x2_sub)
print(x2)

[[4 4]
 [4 7]]
[[99  4]
 [ 4  7]]
[[99  4  0  2]
 [ 4  7  7  9]
 [ 5  1  5  9]]


# criando copias

In [248]:
x2_sub_copy = x2[:2, :2].copy() 
print(x2_sub_copy)
x2_sub_copy[0, 0] = 66 
print(x2_sub_copy)
print(x2)

[[99  4]
 [ 4  7]]
[[66  4]
 [ 4  7]]
[[99  4  0  2]
 [ 4  7  7  9]
 [ 5  1  5  9]]


# salvando e carregando matrizes

In [249]:
!rm -rf /home/silvio/testg.npy
!rm -rf /home/silvio/testg.txt
!rm -rf /home/silvio/testH-c.npz
!rm -rf /home/silvio/testHHH.npz

In [250]:
nHIGH=np.eye(500) 
np.save('/home/silvio/testg',nHIGH) 
np.savetxt('/home/silvio/testg.txt',nHIGH) 
np.savez('/home/silvio/testHHH',nHIGH=nHIGH) 
np.savez_compressed('/home/silvio/testH-c',nHIGH=nHIGH)

In [251]:
!ls -lh /home/silvio/testg.npy
!ls -lh /home/silvio/testg.txt
!ls -lh /home/silvio/testH.npz 
!ls -lh /home/silvio/testH-c.npz

-rw-r--r-- 1 silvio ncc 2.0M Sep 11 10:23 /home/silvio/testg.npy
-rw-r--r-- 1 silvio ncc 6.0M Sep 11 10:23 /home/silvio/testg.txt
-rw-r--r-- 1 silvio ncc 2.0M Sep 10 17:31 /home/silvio/testH.npz
-rw-r--r-- 1 silvio ncc 3.3K Sep 11 10:23 /home/silvio/testH-c.npz


In [253]:
!cat /home/silvio/testg.txt

1.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 

0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 1.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 

0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 

0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 

0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 

0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 0.000000000000000000e+00 

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [254]:
my_array1 = np.loadtxt('/home/silvio/testg.txt') 
print("my_array1: ",my_array1)

my_array2 = np.load('/home/silvio/testg.npy') 
print("my_array2: ",my_array2)

my_array3 = np.load('/home/silvio/testH-c.npz') 
print("my_array3: ",my_array3) 

my_array4 = np.load('/home/silvio/testHHH.npz') 
print("my_array4: ",my_array4) 

my_array1:  [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
my_array2:  [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
my_array3:  <numpy.lib.npyio.NpzFile object at 0x7fb228aea630>
my_array4:  <numpy.lib.npyio.NpzFile object at 0x7fb23707eba8>


In [168]:
my_array3['nHIGH']


array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [255]:
print(my_array3['nHIGH'].nbytes)
print(my_array1.nbytes)

2000000
2000000


In [169]:
my_array4['nHIGH']

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# operações com matrizes
* somando matrizes
* somatória dos elementos da matriz

In [261]:
x=np.random.random((3,4,5)) 
y=np.random.random((3,4,5))


res=np.add(x,y) 
print('res: ',res)

z=x+y 
print('z: ',z)

res:  [[[0.92176016 0.3667972  0.64427339 1.03193881 0.81233761]
  [1.5605005  1.59676294 0.44038521 0.92102961 0.95130445]
  [1.368397   1.34152512 1.12210894 1.53653874 1.15918765]
  [1.39850755 1.15207361 0.91820717 1.30924394 0.6283348 ]]

 [[0.18908996 0.99297253 1.0516463  0.97742207 1.07595727]
  [1.27374507 1.71080683 0.94096409 1.6954593  1.01139044]
  [1.55643542 1.36025158 0.82400669 0.40150901 0.36123282]
  [1.6414821  1.16263987 1.06341348 0.61737305 1.36692191]]

 [[0.68472282 1.1004122  1.49173349 1.07950954 0.49407609]
  [1.13681478 1.04582913 1.07181465 0.60357234 0.98088048]
  [1.22714564 1.61805205 1.21887652 0.81186236 1.68042811]
  [0.47244387 0.70496382 1.30699194 1.41374277 0.47020909]]]
z:  [[[0.92176016 0.3667972  0.64427339 1.03193881 0.81233761]
  [1.5605005  1.59676294 0.44038521 0.92102961 0.95130445]
  [1.368397   1.34152512 1.12210894 1.53653874 1.15918765]
  [1.39850755 1.15207361 0.91820717 1.30924394 0.6283348 ]]

 [[0.18908996 0.99297253 1.0516463  0.

In [258]:
x=np.random.random((3,4)) 
y=np.random.random((5,1,4))


res=np.add(x,y) 
print('res: ',res)

z=x,y 
print('z: ',z)

res2=res.sum() 
print('res2: ',res2)

res:  [[[1.28252268 0.76904341 0.65829239 1.00109785]
  [0.88937715 0.83762391 0.21339337 1.23378062]
  [1.28081518 1.16160953 0.40548358 0.54953844]]

 [[0.61484387 0.20308732 1.39947023 0.64757828]
  [0.22169835 0.27166782 0.95457121 0.88026105]
  [0.61313638 0.59565344 1.14666142 0.19601887]]

 [[0.9035858  0.78982306 0.91670016 1.00678479]
  [0.51044028 0.85840357 0.47180113 1.23946755]
  [0.90187831 1.18238918 0.66389134 0.55522538]]

 [[1.39072434 0.8923663  1.46807066 1.47974415]
  [0.99757881 0.9609468  1.02317163 1.71242692]
  [1.38901684 1.28493242 1.21526185 1.02818474]]

 [[1.12059851 0.45984449 0.70992504 1.58020286]
  [0.72745298 0.528425   0.26502601 1.81288563]
  [1.11889101 0.85241062 0.45711622 1.12864345]]]
z:  (array([[0.45648496, 0.17420858, 0.64913247, 0.62410285],
       [0.06333943, 0.24278908, 0.20423345, 0.85678562],
       [0.45477747, 0.5667747 , 0.39632366, 0.17254344]]), array([[[0.82603772, 0.59483483, 0.00915992, 0.376995  ]],

       [[0.15835891, 0.028

# multiplicaçao de matrizes 

In [257]:
x=np.random.random((3,4)) 
y=np.random.random((3,4))
z=x*y
print(z)

[[0.05113338 0.37645799 0.70689125 0.2174148 ]
 [0.06254341 0.59317561 0.44650421 0.39702707]
 [0.50064086 0.43779758 0.19548862 0.36967396]]


selecionando elementos

In [171]:
my_2d_array=np.random.random((4,4))

print(my_2d_array[1][2])

print(my_2d_array[1,2])

0.3549168090796764
0.3549168090796764


concatenando matrizes

In [264]:
grid = np.array([[1, 2, 3],[4, 5, 6]])

grid2 = np.array([[10, 20, 30],[40, 50, 60]])

np.concatenate([grid, grid2])

#x = np.array([1, 2, 3])

#grid = np.array([[9, 8, 7],[6, 5, 4]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

stack
* vstack -> concatenar no sentido vertical - inclui nova linha

In [265]:
x = np.array([1, 2, 3])
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

stack
* hstack -> concatenar no sentido horizontal - inclui nova coluna

In [266]:
y = np.array([[99],[99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

# parametro axis

In [267]:
x=np.random.random((3,4)) 
print(x)
print(x.sum()) 
print(x.sum(axis=0)) 
print(x.sum(axis=1)) 

[[0.41771213 0.02415562 0.14004811 0.18903374]
 [0.2787148  0.43785583 0.29715293 0.96235775]
 [0.42977358 0.23228777 0.88240273 0.74407539]]
5.03557037581772
[1.12620051 0.69429921 1.31960377 1.89546688]
[0.7709496  1.97608131 2.28853947]


# funcoes diversa
* exponencial
* minimo
* maximo

In [268]:
x = [1, 2, 3] 
print("x =", x)
print("e^x =",np.exp(x)) 
print("2^x =",np.exp2(x)) 
print("3^x =",np.power(3,x))

big_array = np.random.randint(1, 100, size=1000000)
print(min(big_array))
print(max(big_array))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
1
99


# comparando tempo de execução entre função python e funçao numpy

In [269]:
%timeit min(big_array)
%timeit np.min(big_array)

76 ms ± 579 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
561 µs ± 445 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Classificando matrizes numpy

In [270]:
x = np.array([2, 1, 4, 3, 5])
i = np.sort(x)
print(i)

[1 2 3 4 5]


# atributo values transforma um series em numpy array

In [271]:
np_array = np.array([10, 20, 30, 40, 50])

print("NumPy array:")
print(np_array)
print(type(np_array))

new_series = pd.Series(np_array)

print("Pandas series:")
print(new_series)
print(type(new_series))

x=new_series.values

print("NumPy array:")
print(type(x))
print(x)

NumPy array:
[10 20 30 40 50]
<class 'numpy.ndarray'>
Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>
NumPy array:
<class 'numpy.ndarray'>
[10 20 30 40 50]
