In [143]:
import numpy as np
import pandas as pd

# criando array com valores iguais

In [144]:
n = np.ones((3,4))

print("np.ones: ",n)

np.ones:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# criando array com zeros

In [146]:
n=np.zeros((2,3,4),dtype=np.int16) 
print("np.zeros: ",n)

np.zeros:  [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


# criando array com valores aleatorios 

In [147]:
n=np.random.random((2,2)) 
print("random.random: ",n)

random.random:  [[0.48751427 0.58229743]
 [0.37785649 0.35712024]]


# criando array vazias

In [148]:

n=np.empty((3,2)) 
print("empty: ",n)

empty:  [[0. 0.]
 [0. 0.]
 [0. 0.]]


# criando array com valores sequenciais

In [149]:

n=np.arange(10,25,5) 
print("arange: ",n)

arange:  [10 15 20]


In [150]:
* matriz com valores igualmente espacados em um intervalo
* criando matriz identidade, 

SyntaxError: invalid syntax (<ipython-input-150-dec0037ad2e1>, line 1)

In [151]:
n=np.linspace(0,2,10) 
print("linspace: ",n)

n = np.eye(22) 
print("np.eye: ",n)

n = np.identity(5) 
print("np.identity: ",n)

linspace:  [0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]
np.eye:  [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1

# mudando o tipo da matriz
* bool_
* int_
* intc
* intp
* int8
* int16
* int32
* int64
* uint8
* uint16
* uint32
* uint64
* float_
* float16
* float32
* float64
* complex_
* complex64
* complex128

In [152]:
z=np.array([1, 2, 3, 4], dtype='uint64')
z

array([1, 2, 3, 4], dtype=uint64)

In [153]:
z=np.array([9223372036854775805, 9223372036854775806, 9223372036854775807, 9999999999999999999,17999999999999999999,18000000000000000000], dtype='uint64')
z                                                                                                        


array([ 9223372036854775805,  9223372036854775806,  9223372036854775807,
        9999999999999999999, 17999999999999999999, 18000000000000000000],
      dtype=uint64)

In [154]:
z=np.array([9223372036854775805, 9223372036854775806, 9223372036854775807, 9999999999999999999,17999999999999999999,18000000000000000000], dtype='uint32')
z

array([4294967293, 4294967294, 4294967295, 2313682943, 3305635839,
       3305635840], dtype=uint32)

# informação sobre matrizes

* dimensoes
* formato
* quantidade de elementos
* layout de memoria
* tamanho de um elemento em bytes
* tamanho total do array em bytes

In [155]:
my_array=np.full((12,12),70)

print(my_array.ndim)
print(my_array.shape)
print(my_array.size)
print(my_array.flags)
print(my_array.itemsize)
print(my_array.nbytes) 

2
(12, 12)
144
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

8
1152


# mudando o formato - reshape

In [156]:
print(my_array) 

[[70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]
 [70 70 70 70 70 70 70 70 70 70 70 70]]


In [157]:
zz=my_array.reshape(1,144)
print(zz) 

[[70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70
  70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70
  70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70
  70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70
  70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70
  70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70 70]]


# slicing de array
* cinco primeiros
* após quinto elemento
* elementos no meio da matriz
* pulando um elemento
* pulando um elemento comecando do elemento 1
* lista reversa
* lista reversa , pulando um elemento comecando do quinto elemento

In [158]:
x = np.arange(10)
print(x)
print(x[:5]) 
print(x[5:]) 
print(x[4:7]) 
print(x[::2])
print(x[1::2])
print(x[::-1])
print(x[5::-2])    

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


# Matriz multidimensional

In [159]:
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5)) 

In [160]:
x2

array([[1, 7, 5, 9],
       [2, 6, 6, 9],
       [0, 2, 8, 2]])

# slice de matriz multidimensional
* duas linhas e 3 colunas
* todas as linhas pulando uma coluna
* ordem reversa
* primeira coluna
* primeira linha

In [161]:
print(x2[:2, :3])
print(x2[:3, ::2])
print(x2[::-1, ::-1])
print(x2[:, 0])
print(x2[0, :])

[[1 7 5]
 [2 6 6]]
[[1 5]
 [2 6]
 [0 8]]
[[2 8 2 0]
 [9 6 6 2]
 [9 5 7 1]]
[1 2 0]
[1 7 5 9]


# numpy represent variaveis por referencia
* fazendo slice de uma matriz para uma nova matriz, mantem a referencia para o valor original

In [162]:
x2_sub = x2[:2, :2] 
print(x2_sub)
x2_sub[0, 0] = 99 
print(x2_sub)
print(x2)

[[1 7]
 [2 6]]
[[99  7]
 [ 2  6]]
[[99  7  5  9]
 [ 2  6  6  9]
 [ 0  2  8  2]]


# criando copias

In [163]:
x2_sub_copy = x2[:2, :2].copy() 
print(x2_sub_copy)
x2_sub_copy[0, 0] = 66 
print(x2_sub_copy)
print(x2)

[[99  7]
 [ 2  6]]
[[66  7]
 [ 2  6]]
[[99  7  5  9]
 [ 2  6  6  9]
 [ 0  2  8  2]]


# salvando e carregando matrizes

In [164]:
!rm -rf /home/silvio/testg.npy
!rm -rf /home/silvio/testg.txt
!rm -rf /home/silvio/testH-c.npz
!rm -rf /home/silvio/testHHH.npz

In [165]:
nHIGH=np.eye(500) 
np.save('/home/silvio/testg',nHIGH) 
np.savetxt('/home/silvio/testg.txt',nHIGH) 
np.savez('/home/silvio/testHHH',nHIGH=nHIGH) 
np.savez_compressed('/home/silvio/testH-c',nHIGH=nHIGH)

In [166]:
!ls -lh /home/silvio/testg.npy
!ls -lh /home/silvio/testg.txt
!ls -lh /home/silvio/testH.npz 
!ls -lh /home/silvio/testH-c.npz

-rw-r--r-- 1 silvio ncc 2.0M Sep 10 19:04 /home/silvio/testg.npy
-rw-r--r-- 1 silvio ncc 6.0M Sep 10 19:04 /home/silvio/testg.txt
-rw-r--r-- 1 silvio ncc 2.0M Sep 10 17:31 /home/silvio/testH.npz
-rw-r--r-- 1 silvio ncc 3.3K Sep 10 19:04 /home/silvio/testH-c.npz


In [167]:
my_array1 = np.loadtxt('/home/silvio/testg.txt') 
print("my_array1: ",my_array1)

my_array2 = np.load('/home/silvio/testg.npy') 
print("my_array2: ",my_array2)

my_array3 = np.load('/home/silvio/testH-c.npz') 
print("my_array3: ",my_array3) 

my_array4 = np.load('/home/silvio/testHHH.npz') 
print("my_array4: ",my_array4) 

my_array1:  [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
my_array2:  [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
my_array3:  <numpy.lib.npyio.NpzFile object at 0x7fb23707eba8>
my_array4:  <numpy.lib.npyio.NpzFile object at 0x7fb22f97b3c8>


In [168]:
my_array3['nHIGH']

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [169]:
my_array4['nHIGH']

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# operações com matrizes
* somando matrizes
* somatória dos elementos da matriz

In [170]:
x=np.random.random((3,4)) 
y=np.random.random((5,1,4))

res=np.add(x,y) 
print('res: ',res)

res2=res.sum() 
print('res2: ',res2)

res:  [[[1.79854688 1.51162631 1.1831531  1.02757537]
  [0.86201773 0.80851738 1.14491499 0.77778477]
  [1.33074929 1.41229259 1.59672392 0.88855312]]

 [[1.36233559 1.16113371 1.40079991 0.89923389]
  [0.42580644 0.45802478 1.3625618  0.64944329]
  [0.89453799 1.06179999 1.81437073 0.76021164]]

 [[1.18583736 1.50340387 1.43841335 1.80004514]
  [0.24930821 0.80029494 1.40017524 1.55025454]
  [0.71803976 1.40407015 1.85198417 1.66102289]]

 [[1.42024164 1.09363031 1.37626616 1.45959485]
  [0.48371249 0.39052137 1.33802805 1.20980425]
  [0.95244404 0.99429659 1.78983698 1.32057259]]

 [[1.84696666 1.71971035 0.6866819  1.10191509]
  [0.91043751 1.01660142 0.64844379 0.85212449]
  [1.37916906 1.62037663 1.10025272 0.96289284]]]
res2:  69.83008663557062


selecionando elementos

In [171]:
my_2d_array=np.random.random((4,4))

print(my_2d_array[1][2])

print(my_2d_array[1,2])

0.3549168090796764
0.3549168090796764


concatenando matrizes

In [172]:
grid = np.array([[1, 2, 3],[4, 5, 6]])

grid2 = np.array([[10, 20, 30],[40, 50, 60]])

np.concatenate([grid, grid2])

#x = np.array([1, 2, 3])

#grid = np.array([[9, 8, 7],[6, 5, 4]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

stack

In [173]:
x = np.array([1, 2, 3])
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [174]:
y = np.array([[99],[99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

# parametro axis

In [175]:
x=np.random.random((3,4)) 
print(x)
print(x.sum()) 
print(x.sum(axis=0)) 
print(x.sum(axis=1)) 

[[0.75393807 0.77715859 0.2048744  0.01880888]
 [0.80558402 0.1312244  0.21619681 0.65735702]
 [0.77404847 0.04087082 0.47880057 0.05858739]]
4.9174494515498495
[2.33357056 0.94925382 0.89987178 0.73475329]
[1.75477994 1.81036225 1.35230726]


# funcoes diversa
* exponencial
* minimo
* maximo

In [176]:
x = [1, 2, 3] 
print("x =", x)
print("e^x =",np.exp(x)) 
print("2^x =",np.exp2(x)) 
print("3^x =",np.power(3,x))

big_array = np.random.randint(1, 100, size=1000000)
print(min(big_array))
print(max(big_array))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]
1
99


# comparando tempo de execução entre função python e funçao numpy

In [177]:
%timeit min(big_array)
%timeit np.min(big_array)

95 ms ± 2.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
716 µs ± 22.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Classificando matrizes numpy

In [178]:
x = np.array([2, 1, 4, 3, 5])
i = np.sort(x)
print(i)

[1 2 3 4 5]


# atributo values transforma um series em numpy array

In [179]:
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
print(type(np_array))
new_series = pd.Series(np_array)
print("Pandas series:")
print(new_series)
print(type(new_series))
x=new_series.values
print("NumPy array:")

print(type(x))
print(x)

NumPy array:
[10 20 30 40 50]
<class 'numpy.ndarray'>
Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>
NumPy array:
<class 'numpy.ndarray'>
[10 20 30 40 50]
