In [1]:
import numpy as np

In [5]:
#Crie um array com 10 elementos usando a função arange
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
#Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape
twod_arr = arr.reshape(2,5)
twod_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [27]:
#Crie duas matrizes bidimensionais com valores aleatórios
mat1 = np.random.random((2,5))
mat2 = np.random.random((5,2))
print(mat1)
print(mat2)

[[0.78796007 0.3054855  0.42332719 0.00607905 0.82650034]
 [0.6482176  0.81098457 0.98223018 0.2173499  0.54138164]]
[[0.74554689 0.94396632]
 [0.40347575 0.1138586 ]
 [0.54438062 0.45584732]
 [0.70896074 0.57888484]
 [0.77709047 0.82775741]]


In [32]:
#Calcule a transposta de cada matriz
print("Matriz 1")
print(mat1)
transp1 = mat1.transpose()
print(transp1)

print("Matriz 2")
print(mat2)
transp2 = mat2.transpose()
print(transp2)

Matriz 1
[[0.78796007 0.3054855  0.42332719 0.00607905 0.82650034]
 [0.6482176  0.81098457 0.98223018 0.2173499  0.54138164]]
[[0.78796007 0.6482176 ]
 [0.3054855  0.81098457]
 [0.42332719 0.98223018]
 [0.00607905 0.2173499 ]
 [0.82650034 0.54138164]]
Matriz 2
[[0.74554689 0.94396632]
 [0.40347575 0.1138586 ]
 [0.54438062 0.45584732]
 [0.70896074 0.57888484]
 [0.77709047 0.82775741]]
[[0.74554689 0.40347575 0.54438062 0.70896074 0.77709047]
 [0.94396632 0.1138586  0.45584732 0.57888484 0.82775741]]


In [35]:
#multiplique as duas matrizes
mat2_reshaped = mat2.reshape(2,5)
resultmult = mat1 * mat2_reshaped
resultmult

array([[0.58746118, 0.28836803, 0.17080226, 0.00069215, 0.44993076],
       [0.29548825, 0.57495622, 0.56859816, 0.16890054, 0.44813266]])

In [41]:
#Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?
np.savez_compressed('data/matrizes', a=mat1, b=mat2, c=resultmult)


In [43]:
#Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?
#804 bytes
!ls -lh data/matrizes.npz

-rw-r--r-- 1 tiago tiago 804 set 14 14:46 data/matrizes.npz


In [46]:
#Dando load nas matrizes do arquivo
loaded = np.load('data/matrizes.npz')
load_mat1 = loaded['a']
load_mat2 = loaded['b']
load_resultmult = loaded['c']

print(load_mat1)
print(load_mat2)
print(load_resultmult)

[[0.78796007 0.3054855  0.42332719 0.00607905 0.82650034]
 [0.6482176  0.81098457 0.98223018 0.2173499  0.54138164]]
[[0.74554689 0.94396632]
 [0.40347575 0.1138586 ]
 [0.54438062 0.45584732]
 [0.70896074 0.57888484]
 [0.77709047 0.82775741]]
[[0.58746118 0.28836803 0.17080226 0.00069215 0.44993076]
 [0.29548825 0.57495622 0.56859816 0.16890054 0.44813266]]


In [50]:
#Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linha
randmat1 = np.random.random((2,5))
randmat2 = np.random.random((3,5))
concatmat = np.concatenate([randmat1, randmat2])
print("Matriz 1", randmat1)
print("Matriz 2", randmat2)
print("Matriz concat", concatmat)

Matriz 1 [[0.06644652 0.35014403 0.33045319 0.63980434 0.81078304]
 [0.9145431  0.05110358 0.78350814 0.14250694 0.04491837]]
Matriz 2 [[0.5253619  0.66810002 0.41897864 0.28518876 0.42232401]
 [0.67247284 0.99793907 0.5161783  0.94183886 0.54656988]
 [0.38276656 0.89368537 0.38749068 0.21857088 0.64541576]]
Matriz concat [[0.06644652 0.35014403 0.33045319 0.63980434 0.81078304]
 [0.9145431  0.05110358 0.78350814 0.14250694 0.04491837]
 [0.5253619  0.66810002 0.41897864 0.28518876 0.42232401]
 [0.67247284 0.99793907 0.5161783  0.94183886 0.54656988]
 [0.38276656 0.89368537 0.38749068 0.21857088 0.64541576]]


In [51]:
#Crie um vetor nulo de tamanho 10
vetnull = np.zeros(10)
vetnull

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [57]:
#Como encontrar o tamanho da memória de qualquer matriz
concatmat.nbytes

200

In [58]:
#Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1
vetnull = np.zeros(10)
vetnull[4] = 1
vetnull

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [61]:
#Crie um vetor com valores que variam de 10 a 49
vet = np.arange(10,49,3)
vet

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46])

In [63]:
#Inverter um vetor (o primeiro elemento se torna o último)
invert = vet[::-1]
invert

array([46, 43, 40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10])

In [76]:
#Crie uma matriz 3x3 com valores que variam de 0 a 8
mat = np.arange(0,9).reshape((3, 3))
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
#Crie uma matriz de identidade 3x3
identidade = np.identity(3) 
identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
#Crie uma matriz 3x3x3 com valores aleatórios
random = np.random.random((3,3,3))
random

array([[[0.06344132, 0.98791237, 0.25802094],
        [0.99356136, 0.6690468 , 0.38297153],
        [0.45591409, 0.0712005 , 0.73347873]],

       [[0.09990236, 0.47841234, 0.0983479 ],
        [0.8820776 , 0.37351122, 0.82613358],
        [0.21879083, 0.50057412, 0.92773284]],

       [[0.34217608, 0.66454249, 0.58427751],
        [0.54836118, 0.39577568, 0.08033451],
        [0.18648154, 0.18122978, 0.7320218 ]]])

In [85]:
#Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo
random = np.random.random((10,10))
print("Min: ", random.min())
print("Max: ", random.max())

Min:  0.005274524311942863
Max:  0.9904339972292602


In [88]:
#Crie um vetor aleatório de tamanho 30 e encontre o valor médio
vet = np.random.rand(30)
vet.mean()

0.5550025414464997

In [91]:
#Crie uma matriz 2D com 1 na borda e 0 dentro
matriz = np.ones(9)
matriz[4] = 0
matriz.reshape(3,3)

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [120]:
#Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal
matriz = np.zeros((5,5), dtype=int)
matriz += np.arange(1,6)
matriz

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [153]:
#Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)
estruturado = np.array([((33.3,122), (0,0,0)), ((44.4,12.3), (255,255,255))])
estruturado

array([[(33.3, 122), (0, 0, 0)],
       [(44.4, 12.3), (255, 255, 255)]], dtype=object)

In [159]:
#Subtrair a média de cada linha de uma matriz
matriz = 
matriz2 = matriz - matriz.mean(axis=1)
matriz2

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [228]:
#Como encontrar o valor mais frequente em uma matriz?
matrix = np.array([1,2,3,5,5,3,2,13,13,2]).reshape(2,5)
print(matrix)
array, count = np.unique(matrix,return_counts=True)
index = np.argmax(count, axis=0)
print("Mais frequente:",array[index])

[[ 1  2  3  5  5]
 [ 3  2 13 13  2]]
Mais frequente: 2


In [207]:
#Crie uma matriz a partir de um arquivo
loaded = np.load('data/matrizes.npz')
load_mat1 = loaded['a']
load_mat2 = loaded['b']
load_resultmult = loaded['c']

print(load_mat1)
print(load_mat2)
print(load_resultmult)

[[0.78796007 0.3054855  0.42332719 0.00607905 0.82650034]
 [0.6482176  0.81098457 0.98223018 0.2173499  0.54138164]]
[[0.74554689 0.94396632]
 [0.40347575 0.1138586 ]
 [0.54438062 0.45584732]
 [0.70896074 0.57888484]
 [0.77709047 0.82775741]]
[[0.58746118 0.28836803 0.17080226 0.00069215 0.44993076]
 [0.29548825 0.57495622 0.56859816 0.16890054 0.44813266]]


In [214]:
#Crie uma matriz com valores aletaórios e salve para um arquivo
mat = np.random.random((10,5))
mat
np.savez_compressed('data/mat', matriz = mat)


In [215]:
load = np.load('data/mat.npz')
load['matriz']

array([[0.76215019, 0.83502323, 0.61199794, 0.93587521, 0.0555312 ],
       [0.51052815, 0.25435462, 0.32116645, 0.10828829, 0.41606023],
       [0.59108403, 0.85983295, 0.67189776, 0.02216063, 0.79888448],
       [0.39403765, 0.26367392, 0.35014225, 0.96883438, 0.22977055],
       [0.03840791, 0.4597771 , 0.36772284, 0.51524065, 0.43586692],
       [0.36950961, 0.96130258, 0.33219225, 0.62127395, 0.41091532],
       [0.041324  , 0.20992836, 0.37746273, 0.71909341, 0.24014873],
       [0.85000927, 0.61501686, 0.6065993 , 0.38117545, 0.36145993],
       [0.3559592 , 0.82268044, 0.91169467, 0.74669901, 0.8720074 ],
       [0.53861809, 0.83267167, 0.07392521, 0.41977755, 0.21810611]])