### Exercícios Numpy

Crie um array com 10 elementos usando a função arange

In [2]:
import numpy as np

In [28]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape

In [43]:
novo_array = np.reshape(array,(2,5))
novo_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Crie duas matrizes bidimensionais com valores aleatórios

In [53]:
matriz_1 = np.random.rand(2,5)
matriz_2 = np.random.rand(2,5)
print ("Matriz 1: \n", matriz_1, "\n")
print ("Matriz 2: \n", matriz_2, "\n")

Matriz 1: 
 [[0.93441964 0.46528858 0.87783579 0.66952287 0.41907906]
 [0.34657064 0.71755495 0.50084924 0.79281005 0.10396641]] 

Matriz 2: 
 [[0.26766107 0.63001885 0.16142108 0.32036568 0.08408754]
 [0.39286161 0.11323316 0.26170863 0.95928708 0.12312165]] 



calcule a transposta de cada matriz

In [54]:
matriz_1_transposta = matriz_1.transpose()
matriz_2_transposta = matriz_2.transpose()
print ("Matriz 1 transposta: \n", matriz_1_transposta, "\n")
print ("Matriz 2 transposta: \n", matriz_2_transposta, "\n")

Matriz 1 transposta: 
 [[0.93441964 0.34657064]
 [0.46528858 0.71755495]
 [0.87783579 0.50084924]
 [0.66952287 0.79281005]
 [0.41907906 0.10396641]] 

Matriz 2 transposta: 
 [[0.26766107 0.39286161]
 [0.63001885 0.11323316]
 [0.16142108 0.26170863]
 [0.32036568 0.95928708]
 [0.08408754 0.12312165]] 



multiplique as duas matrizes

In [61]:
matriz_2_transposta = matriz_2_transposta.transpose()
produto = np.dot(matriz_1_transposta,matriz_2_transposta)
print ("Produto: \n", produto)

Produto: 
 [[0.38626206 0.62794528 0.24153555 0.63181672 0.1212434 ]
 [0.40643944 0.37439159 0.26289771 0.83740368 0.12747152]
 [0.43172691 0.60976584 0.27277777 0.76168666 0.13548043]
 [0.49066984 0.51158442 0.31556033 0.97502458 0.15391061]
 [0.15301556 0.27580015 0.0948571  0.23399218 0.04803984]]


Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?

In [ ]:
'''
Outra forma

num_l = int(input("Digite a quantidade de linhas da matriz aleatória: "))
num_c = int(input("Digite a quantidade de colunas da matriz aleatória: "))
matriz_aleatoria = np.random.rand(num_l,num_c)
print ("\n", matriz_aleatoria)
#!touch arquivo.txt
writeFile = open ("arquivo.txt", "a")
writeFile.write(str(matriz_aleatoria) + '\n\n' )
writeFile.close()
matriz_1_transposta = matriz_aleatoria.transpose()
produto = np.dot(matriz_aleatoria,matriz_1_transposta)
writeFile = open ("arquivo.txt", "a")
writeFile.write(str(produto) + '\n' )
writeFile.close()
'''

In [109]:
num_l = int(input("Digite a quantidade de linhas da matriz aleatória: "))
num_c = int(input("Digite a quantidade de colunas da matriz aleatória: "))
matriz_aleatoria = np.random.rand(num_l,num_c)
print ("\n", matriz_aleatoria)
#!touch arquivo.txt

np.savetxt('arquivo.txt',matriz_aleatoria) 

matriz_1_transposta = matriz_aleatoria.transpose()
produto = np.dot(matriz_aleatoria,matriz_1_transposta)

np.savetxt('arquivo.txt',matriz_aleatoria) 

Digite a quantidade de linhas da matriz aleatória: 2
Digite a quantidade de colunas da matriz aleatória: 25

 [[5.33498712e-01 4.17426208e-01 8.70065643e-01 3.45729444e-02
  6.68793800e-01 4.85035427e-01 1.78041151e-01 7.92355856e-01
  1.39206950e-01 8.55707707e-01 8.31030182e-01 3.96956676e-01
  7.72245044e-01 1.74341626e-02 9.79072430e-01 4.10207588e-01
  7.44083258e-01 3.34500961e-01 6.37653102e-02 1.83546765e-01
  4.43844729e-01 8.41570340e-01 5.51053953e-01 9.50632040e-01
  9.20688787e-01]
 [6.77908524e-01 6.91984145e-01 2.10495775e-01 1.75044210e-01
  5.75579953e-01 6.95940280e-01 6.03488733e-01 3.60276619e-02
  6.85183542e-01 7.80758160e-01 9.51462029e-01 1.66876057e-01
  5.12700454e-01 3.37089716e-04 3.98512364e-01 7.90000198e-01
  3.52837657e-02 5.43355701e-01 4.23352790e-01 8.17291394e-02
  2.19229912e-01 2.52156504e-01 3.96984421e-01 7.22820397e-02
  1.77164443e-01]]


In [110]:
!ls -lh arquivo.txt

-rw-rw-r-- 1 karentaniguchi karentaniguchi 1,3K set 14 16:19 arquivo.txt


In [75]:
!cat arquivo.txt

[[0.37756159 0.51522916 0.38451067]
 [0.38848804 0.48888876 0.94669152]
 [0.18278276 0.90085198 0.99947209]]

[[0.5558623  0.7625809  0.91746465]
 [0.7625809  1.28616002 1.45761708]
 [0.91746465 1.45761708 1.84388829]]


Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linha

In [102]:
m_1 = np.random.rand(3,3)
m_2 = np.random.rand(3,3)
print ("Matriz 1: \n", m_1, "\n")
print ("Matriz 2: \n", m_2, "\n")
m1 = np.split(m_1,3)
m2 = np.split(m_2,3)
m = np.concatenate((m1, m2))
print ("Matriz combinada: \n", m, "\n")

Matriz 1: 
 [[0.37799749 0.30859988 0.9480525 ]
 [0.11933269 0.51462523 0.09303803]
 [0.48217473 0.46955023 0.62257113]] 

Matriz 2: 
 [[0.70174984 0.48232867 0.89680262]
 [0.64302335 0.61029775 0.97817906]
 [0.47362519 0.46870051 0.55614345]] 

Matriz combinada: 
 [[[0.37799749 0.30859988 0.9480525 ]]

 [[0.11933269 0.51462523 0.09303803]]

 [[0.48217473 0.46955023 0.62257113]]

 [[0.70174984 0.48232867 0.89680262]]

 [[0.64302335 0.61029775 0.97817906]]

 [[0.47362519 0.46870051 0.55614345]]] 



Crie um vetor nulo de tamanho 10

In [104]:
nulos = np.zeros(10)
nulos

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Como encontrar o tamanho da memória de qualquer matriz

In [111]:
matriz = np.random.rand(3,3)

In [112]:
print(matriz.nbytes)

72


Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1

In [117]:
zeros = np.zeros(4)
um = np.eye(1)
zeros_um = np.append(zeros,um)
zeros_um = np.append(zeros_um,zeros)
print(zeros_um)

[0. 0. 0. 0. 1. 0. 0. 0. 0.]


Crie um vetor com valores que variam de 10 a 49

In [120]:
vetor = np.linspace(10,49)
vetor

array([10.        , 10.79591837, 11.59183673, 12.3877551 , 13.18367347,
       13.97959184, 14.7755102 , 15.57142857, 16.36734694, 17.16326531,
       17.95918367, 18.75510204, 19.55102041, 20.34693878, 21.14285714,
       21.93877551, 22.73469388, 23.53061224, 24.32653061, 25.12244898,
       25.91836735, 26.71428571, 27.51020408, 28.30612245, 29.10204082,
       29.89795918, 30.69387755, 31.48979592, 32.28571429, 33.08163265,
       33.87755102, 34.67346939, 35.46938776, 36.26530612, 37.06122449,
       37.85714286, 38.65306122, 39.44897959, 40.24489796, 41.04081633,
       41.83673469, 42.63265306, 43.42857143, 44.2244898 , 45.02040816,
       45.81632653, 46.6122449 , 47.40816327, 48.20408163, 49.        ])

Inverter um vetor (o primeiro elemento se torna o último)

In [125]:
vetor = np.linspace(10,49)
inverso = np.flip(vetor)
inverso

array([49.        , 48.20408163, 47.40816327, 46.6122449 , 45.81632653,
       45.02040816, 44.2244898 , 43.42857143, 42.63265306, 41.83673469,
       41.04081633, 40.24489796, 39.44897959, 38.65306122, 37.85714286,
       37.06122449, 36.26530612, 35.46938776, 34.67346939, 33.87755102,
       33.08163265, 32.28571429, 31.48979592, 30.69387755, 29.89795918,
       29.10204082, 28.30612245, 27.51020408, 26.71428571, 25.91836735,
       25.12244898, 24.32653061, 23.53061224, 22.73469388, 21.93877551,
       21.14285714, 20.34693878, 19.55102041, 18.75510204, 17.95918367,
       17.16326531, 16.36734694, 15.57142857, 14.7755102 , 13.97959184,
       13.18367347, 12.3877551 , 11.59183673, 10.79591837, 10.        ])

Crie uma matriz 3x3 com valores que variam de 0 a 8

In [145]:
matriz_3_3 = np.random.randint(8, size=(3, 3))
matriz_3_3

array([[5, 3, 2],
       [2, 4, 5],
       [1, 5, 3]])

Crie uma matriz de identidade 3x3

In [147]:
identidade = np.eye(3,3)
identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Crie uma matriz 3x3x3 com valores aleatórios

In [6]:
matriz_3_3_3 = np.random.randint(100, size=(3, 3, 3))
matriz_3_3_3

array([[[28, 84, 52],
        [38, 37, 27],
        [17, 85, 82]],

       [[25, 96, 49],
        [64, 94, 52],
        [96, 10, 36]],

       [[35, 49, 45],
        [53, 60, 28],
        [24, 73, 75]]])

Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo

In [4]:
matriz_10_10 = np.random.randint(low=12, high=100, size=(10, 10))
minimo = np.min(matriz_10_10)
maximo = np.max(matriz_10_10)
print(matriz_10_10)
print("\nMínimo: ", minimo)
print("Máximo: ", maximo)

[[18 34 44 71 30 12 97 91 66 70]
 [60 91 75 45 69 53 34 20 87 79]
 [44 82 30 12 50 79 12 54 84 39]
 [70 43 15 41 56 75 57 62 82 84]
 [73 66 45 96 26 18 87 50 16 26]
 [91 73 29 82 91 39 78 63 36 47]
 [95 86 45 63 19 51 92 87 41 57]
 [95 76 34 73 69 57 77 52 54 31]
 [17 90 61 98 89 61 56 64 78 70]
 [93 24 87 56 24 33 67 41 22 67]]

Mínimo:  12
Máximo:  98


Crie um vetor aleatório de tamanho 30 e encontre o valor médio

In [28]:
matriz_30 = np.random.randint(100,size=(1, 30))
print(matriz_30)
media = np.mean(matriz_30)
print("\nMédia: ", media)

[[15  5 57 76 80 35 66 30 39 96 25 53 50 65 73 62 43 55  8 20 19 52  5 67
  22 15 21 23 15 55]]

Média:  41.56666666666667


Crie uma matriz 2D com 1 na borda e 0 dentro

In [10]:
array_2d = np.array([[1, 0, 1],[1, 0, 1]])
array_2d

array([[1, 0, 1],
       [1, 0, 1]])

Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal

In [90]:
matriz = (5,5)
matriz_5_5 = np.zeros(matriz)

for i in range(len(matriz_5_5)):
    for j in range(len(matriz_5_5)):
        if (i != 0) and ((i != j)) and (i == j+1) :
            matriz_5_5[i,j] = i
            
print(matriz_5_5)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)

In [30]:
matriz_estruturada = np.array([[0, 0, 0],[0, 1, 0]])
print('   r g b')
print('x',matriz_estruturada[0])
print('y',matriz_estruturada[1])

   r g b
x [0 0 0]
y [0 1 0]


Subtrair a média de cada linha de uma matriz

In [25]:
matriz_2_2 = np.random.randint(10, size=(2, 2))
media = np.mean(matriz_2_2)
print("Matriz: \n", matriz_2_2)
print("\nMédia: ", media)
for i in range(len(matriz_2_2)):
    for j in range(len(matriz_2_2)):
            matriz_2_2[i,j] = media - matriz_2_2[i,j]
print('Média de cada linha de uma matriz: \n', matriz_2_2)            

Matriz: 
 [[0 6]
 [8 6]]

Média:  5.0
Média de cada linha de uma matriz: 
 [[ 5 -1]
 [-3 -1]]


Como encontrar o valor mais frequente em uma matriz?


In [28]:
vetor = np.array([12,12,12,5,6,7,7,5])
print(vetor)
conta = np.bincount(vetor)
print ('\nValor mais frequente: ', np.argmax(conta))

[12 12 12  5  6  7  7  5]

Valor mais frequente:  12


Crie uma matriz a partir de um arquivo

In [29]:
matriz_arquivo = np.eye(2)
np.savetxt('arquivo.txt',matriz_arquivo) 

crie uma matriz com valores aleatórios e salve para um arquivo

In [115]:
num_l = int(input("Digite a quantidade de linhas da matriz aleatória: "))
num_c = int(input("Digite a quantidade de colunas da matriz aleatória: "))
matriz_aleatoria = np.random.rand(num_l,num_c)
print ("\n", matriz_aleatoria)

np.savetxt('arquivo.txt',matriz_aleatoria) 

Digite a quantidade de linhas da matriz aleatória: 3
Digite a quantidade de colunas da matriz aleatória: 3
