In [110]:
import numpy as np 
import pandas as pd
from scipy import stats

1. Crie um array com 10 elementos usando a função arange

In [5]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


2. Transforme esse array de 1D (1x10) para 2D (2x5) usando a função reshape

In [6]:
b = a.reshape((2, 5))
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


3. Crie duas matrizes bidimensionais com valores aleatórios

In [70]:
c = np.random.randint(100, size=(3, 4))
d = np.matrix(d)
print(c)
print()
d = np.random.randint(100, size=(4, 3))
d = np.matrix(d)
print(d)

[[31 88 62 98]
 [39 44 43 38]
 [94 52 68 96]]

[[75 94 22]
 [39 55 72]
 [ 3 57 43]
 [39 77 64]]


4. Calcule a transposta de cada matriz

In [71]:
print(c.T)
print()
print(d.T)

[[31 39 94]
 [88 44 52]
 [62 43 68]
 [98 38 96]]

[[75 39  3 39]
 [94 55 57 77]
 [22 72 43 64]]


5. Multiplique as duas matrizes

In [72]:
e = c*d
print(e)

[[ 9765 18834 15956]
 [ 6252 11463  8307]
 [13026 22964 14880]]


6. Salve as matrizes de entrada e a de saída em arquivos. Qual o tamanho dos arquivos gerados?


In [73]:
np.savetxt('c', c)
np.savetxt('d', d)
np.savetxt('c*d', e)
print('Tamanho dos arquivos em bytes:')
print('c:', os.path.getsize ('c'))
print('d:', os.path.getsize ('d'))
print('c*d:', os.path.getsize ('c*d'))

Tamanho dos arquivos em bytes:
c: 300
d: 300
c*d: 225


7. Crie duas bidimensionais matrizes com valores aleatórios e gere uma única matriz combinando linha a linha

In [75]:
f = np.random.randint(100, size=(2, 3))
f = np.matrix(f)
print(f)
print()
g = np.random.randint(100, size=(2, 3))
g = np.matrix(g)
print(g)
print()
h = np.concatenate((f,g))
print(h)

[[37 70 99]
 [ 9 97 48]]

[[ 4 62  6]
 [53 55 59]]

[[37 70 99]
 [ 9 97 48]
 [ 4 62  6]
 [53 55 59]]


8. Crie um vetor nulo de tamanho 10

In [58]:
i = np.zeros(10)
print(i)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


9. Como encontrar o tamanho da memória de qualquer matriz

In [76]:
# Tamanho da matriz f em bytes (por exemplo)
print(f.nbytes)

48


10. Crie um vetor nulo de tamanho 10, mas o quinto valor, que é 1

In [59]:
j = np.zeros(10)
j[5] = 1
print(j)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


11. Crie um vetor com valores que variam de 10 a 49

In [61]:
k = np.arange(10,50)
print(k)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


12. Inverter um vetor (o primeiro elemento se torna o último)

In [64]:
# Invertendo o vetor k (acima)
print(k[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


13. Crie uma matriz 3x3 com valores que variam de 0 a 8

In [82]:
l = np.random.randint(9, size=(3, 3))
print(l)

[[0 3 0]
 [3 0 4]
 [3 8 1]]


14. Crie uma matriz de identidade 3x3

In [83]:
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


15. Crie uma matriz 3x3x3 com valores aleatórios

In [84]:
n = np.random.randint(100, size=(3, 3, 3))
print(n)

[[[93 62 62]
  [62 99 51]
  [72 34 52]]

 [[ 4 19 25]
  [43 31 24]
  [21 41 48]]

 [[66 94 67]
  [12 62 77]
  [ 3 21 17]]]


16. Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo

In [91]:
o = np.random.randint(100, size=(10, 10))
print(o)

print('O valor mínimo é:', np.min(o))
print('O valor máximo é:', np.max(o))

[[25 68 37 26 62 59 19 41 85 32]
 [40 60  8 11 19 39 74 22  2 98]
 [70 42  3 89 52 47 91 83 87 27]
 [94 32 45 40 73 53 52 38 23 36]
 [18 62 93 90 69 63 32 99 50 98]
 [14  0 20 64 84 96 84 53 15 89]
 [45 86 18 85  1 10 42 19 50 68]
 [ 7  8 65  1  8 31 92 94 95 67]
 [69  4 55 32 35 71 69 94 32 17]
 [ 8 27 55 62 93 18 83 14 83 40]]
O valor mínimo é: 0
O valor máximo é: 99


17. Crie um vetor aleatório de tamanho 30 e encontre o valor médio

In [93]:
p = np.random.randint(100, size=30)
print(p)
np.mean(p)

[45 44 86 60 36 63 95 49 42 29 38 76 21 10 24 23 73 80 39 65  5 77  5 78
 29 36 51 35 90  4]


46.93333333333333

18. Crie uma matriz 2D com 1 na borda e 0 dentro

In [95]:
q = np.ones((5,5))
q[1:4, 1:4] = 0
print(q)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


19. Crie uma matriz 5x5 com valores 1,2,3,4 logo abaixo da diagonal

In [120]:
r = np.zeros((5,5))
r[1,0] = 1
r[2,1] = 2
r[3,2] = 3
r[4,3] = 4
print(r)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


20. Crie uma matriz estruturada representando uma posição (x, y) e uma cor (r, g, b)

21. Subtrair a média de cada linha de uma matriz

In [104]:
t = np.random.randint(100, size=(2, 2))
print(t)
u = np.mean(t)
print(u)
print(t-u)


[[ 9 80]
 [50 21]]
40.0
[[-31.  40.]
 [ 10. -19.]]


22. Como encontrar o valor mais frequente em uma matriz?

In [116]:
v = np.random.randint(10, size=(4, 4))
print(v)
stats.mode(v, axis=None)

[[9 0 5 0]
 [2 8 2 6]
 [0 1 5 8]
 [5 9 6 7]]


ModeResult(mode=array([0]), count=array([3]))

23. Crie uma matriz a partir de um arquivo

In [128]:
arq = open('dados_matrix', 'r')  #abre o arquivo
texto = []  #declaro um vetor
matriz = [] #declaro um segundo vetor
texto = arq.readlines() #quebra as linhas do arquivo em vetores 

for i in range(len(texto)):          #esse for percorre a posições do vetor texto
    matriz.append(texto[i].split())  #aqui eu quebro nos espaços das palavra
arq.close() #comando para fechar o arquivo

x = np.array([matriz])
x = x.reshape(2,5)
x = np.matrix(x)
print(x)

[['10' '20' '30' '40' '50']
 ['20' '10' '10' '8' '7']]


24. Crie uma matriz com valores aletaórios e salve para um arquivo

In [130]:
y = np.random.randint(100, size=(4, 4))
np.savetxt('testey.txt',y) 